name: iwslt22_cu113

channels:
- pytorch
- conda-forge
- defaults

dependencies:
- pip=22.0.3
- python=3.7.10
- pytorch=1.10.2
- torchaudio=0.10.2
- cudatoolkit=11.3
- editdistance=0.6.0
- sacrebleu=1.4.13
- fairscale=0.4.3
- sentencepiece=0.1.95
- wandb=0.12.7
- tensorboardx=2.5
- pysoundfile=0.10.3.post1

- pip:
  - wavaugment==0.2
